"""Comentarios de columna en PostgreSQL (paridad con los modelos SQLAlchemy).

Revision: 0008_column_comments
Revision anterior: 0007_schema_alignment

Documenta cada campo en el propio esquema (psql \d+ <tabla>) y permite que
`alembic check` confirme que migraciones y modelos estan alineados.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0008_column_comments"
down_revision: Union[str, None] = "0007_schema_alignment"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("COMMENT ON COLUMN audit_events.timestamp_utc IS 'Timestamp exacto del evento en UTC'")
    op.execute("COMMENT ON COLUMN audit_events.user_id IS 'ID del usuario que ejecutó la acción (nullable para no autenticados)'")
    op.execute("COMMENT ON COLUMN audit_events.user_email IS 'Correo del usuario que ejecutó la acción'")
    op.execute("COMMENT ON COLUMN audit_events.action IS 'Acción ejecutada (AuditAction: CREATE, UPDATE, DELETE, LOGIN...)'")
    op.execute("COMMENT ON COLUMN audit_events.entity_name IS 'Entidad afectada (ej. User, Employee, Publication)'")
    op.execute("COMMENT ON COLUMN audit_events.entity_id IS 'Identificador único del registro afectado'")
    op.execute("COMMENT ON COLUMN audit_events.previous_state IS 'Estado previo serializado en JSON'")
    op.execute("COMMENT ON COLUMN audit_events.new_state IS 'Nuevo estado serializado en JSON'")
    op.execute("COMMENT ON COLUMN audit_events.correlation_id IS 'Identificador de correlación para trazabilidad extremo a extremo'")
    op.execute("COMMENT ON COLUMN audit_events.ip_address IS 'Dirección IP de origen de la solicitud'")
    op.execute("COMMENT ON COLUMN audit_events.user_agent IS 'User-Agent del cliente HTTP'")
    op.execute("COMMENT ON COLUMN audit_events.details IS 'Metadatos contextuales adicionales del evento'")
    op.execute("COMMENT ON COLUMN audit_events.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN employee_history.employee_id IS 'Funcionario al que pertenece el historial'")
    op.execute("COMMENT ON COLUMN employee_history.effective_date IS 'Momento exacto en UTC en que se registró el cambio'")
    op.execute("COMMENT ON COLUMN employee_history.change_reason IS 'Motivo del cambio (ej. Transferencia interna, Promoción, Desvinculación)'")
    op.execute("COMMENT ON COLUMN employee_history.recorded_by_user_id IS 'Usuario que ejecutó o importó la modificación'")
    op.execute("COMMENT ON COLUMN employee_history.correlation_id IS 'Correlation ID para trazabilidad extremo a extremo'")
    op.execute("COMMENT ON COLUMN employee_history.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN employees.employee_id IS 'Identificador único institucional inmutable (Principio VII)'")
    op.execute("COMMENT ON COLUMN employees.document_number_encrypted IS 'Cédula de identidad cifrada con Fernet/AES-256 (Principio XX)'")
    op.execute("COMMENT ON COLUMN employees.document_hash IS 'Blind Index determinista (HMAC-SHA256) para búsquedas exactas'")
    op.execute("COMMENT ON COLUMN employees.first_name IS 'Nombres del funcionario (CONFIDENCIAL)'")
    op.execute("COMMENT ON COLUMN employees.last_name IS 'Apellidos del funcionario (CONFIDENCIAL)'")
    op.execute("COMMENT ON COLUMN employees.organizational_unit_id IS 'Unidad organizacional actual a la que pertenece'")
    op.execute("COMMENT ON COLUMN employees.direction_name IS 'Dirección o dependencia superior del funcionario'")
    op.execute("COMMENT ON COLUMN employees.position_id IS 'Cargo actual desempeñado'")
    op.execute("COMMENT ON COLUMN employees.created_by_user_id IS 'Usuario que creó o gestiona este funcionario en su panel individual'")
    op.execute("COMMENT ON COLUMN employees.status IS 'Estado del funcionario: ACTIVE, INACTIVE, ON_LEAVE, TERMINATED'")
    op.execute("COMMENT ON COLUMN employees.hire_date IS 'Fecha de ingreso institucional'")
    op.execute("COMMENT ON COLUMN employees.termination_date IS 'Fecha de desvinculación (si aplica)'")
    op.execute("COMMENT ON COLUMN employees.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN employees.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.platform_id IS 'Plataforma externa sobre la que se ejecutó el trabajo'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.institutional_account_id IS 'Cuenta institucional sincronizada (si aplica)'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.job_type IS 'Tipo de trabajo: FETCH_POSTS, FETCH_COMMENTS, FETCH_METRICS, VERIFY_INTERACTIONS'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.status IS 'Estado canónico de la máquina de estados de sincronización'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.started_at IS 'Timestamp UTC de inicio de la tarea'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.completed_at IS 'Timestamp UTC de finalización (éxito o fallo)'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.error_details IS 'Descripción detallada de fallos o tracebacks cuando aplique'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.retry_count IS 'Número de reintentos ejecutados bajo backoff exponencial'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.api_version IS 'Versión de la API externa utilizada durante la ejecución'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.correlation_id IS 'ID de correlación distribuida'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN external_sync_jobs.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN institutional_accounts.external_page_id IS 'Identificador único de la página o canal en la plataforma'")
    op.execute("COMMENT ON COLUMN institutional_accounts.account_name IS 'Nombre de la cuenta oficial (ej. Gobierno Autónomo Municipal de El Alto)'")
    op.execute("COMMENT ON COLUMN institutional_accounts.handle IS 'Handle o @usuario (ej. @ElAltoAlcaldia)'")
    op.execute("COMMENT ON COLUMN institutional_accounts.access_token_encrypted IS 'Token de acceso para APIs oficiales (cifrado con Fernet)'")
    op.execute("COMMENT ON COLUMN institutional_accounts.token_expires_at IS 'Expiración del token oficial'")
    op.execute("COMMENT ON COLUMN institutional_accounts.is_monitored IS 'Indica si sus publicaciones e interacciones son monitoreadas activamente'")
    op.execute("COMMENT ON COLUMN institutional_accounts.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN institutional_accounts.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN institutional_accounts.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN interaction_evidences.interaction_id IS 'Interacción respaldada por esta evidencia'")
    op.execute("COMMENT ON COLUMN interaction_evidences.evidence_type IS 'Tipo de evidencia: API_RESPONSE, SCREENSHOT, MANUAL_NOTE, WEBHOOK_PAYLOAD'")
    op.execute("COMMENT ON COLUMN interaction_evidences.content IS 'Payload JSON o contenido textual de la evidencia'")
    op.execute("COMMENT ON COLUMN interaction_evidences.content_hash IS 'Hash criptográfico SHA-256 del contenido para verificar integridad'")
    op.execute("COMMENT ON COLUMN interaction_evidences.created_by_user_id IS 'ID del usuario operador o del worker de ingesta'")
    op.execute("COMMENT ON COLUMN interaction_evidences.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN interaction_evidences.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN interactions.publication_id IS 'Publicación monitoreada sobre la que ocurrió la interacción'")
    op.execute("COMMENT ON COLUMN interactions.platform_id IS 'Plataforma de red social'")
    op.execute("COMMENT ON COLUMN interactions.interaction_type IS 'Tipo canónico: COMMENT, LIKE, SHARE, REPLY'")
    op.execute("COMMENT ON COLUMN interactions.external_interaction_id IS 'ID único externo de la interacción en la plataforma'")
    op.execute("COMMENT ON COLUMN interactions.external_post_id IS 'ID externo del post en la red social'")
    op.execute("COMMENT ON COLUMN interactions.external_author_id IS 'ID de usuario/autor en la plataforma social (ej. Graph API user ID)'")
    op.execute("COMMENT ON COLUMN interactions.external_author_name IS 'Nombre visible o display name del autor'")
    op.execute("COMMENT ON COLUMN interactions.content_text IS 'Texto del comentario o respuesta'")
    op.execute("COMMENT ON COLUMN interactions.reaction_type IS 'Tipo específico de reacción (LIKE, LOVE, CARE, HAHA, WOW, SAD, ANGRY)'")
    op.execute("COMMENT ON COLUMN interactions.external_created_at IS 'Fecha y hora de emisión original en la red social (UTC)'")
    op.execute("COMMENT ON COLUMN interactions.captured_at IS 'Fecha y hora de captura e ingesta en el sistema (UTC)'")
    op.execute("COMMENT ON COLUMN interactions.capture_method IS 'Método de captura: WEBHOOK, POLLING, MANUAL_IMPORT, BACKFILL'")
    op.execute("COMMENT ON COLUMN interactions.api_version IS 'Versión del endpoint de la API utilizada (ej. v26.0)'")
    op.execute("COMMENT ON COLUMN interactions.data_origin_type IS 'Categoría epistémica de origen (Principio V)'")
    op.execute("COMMENT ON COLUMN interactions.source_platform IS 'Nombre canónico de la red social de origen'")
    op.execute("COMMENT ON COLUMN interactions.source_account_id IS 'Cuenta institucional receptora'")
    op.execute("COMMENT ON COLUMN interactions.raw_payload_ref IS 'Hash SHA-256 o referencia JSON de almacenamiento del payload crudo'")
    op.execute("COMMENT ON COLUMN interactions.correlation_id IS 'ID de correlación distribuida'")
    op.execute("COMMENT ON COLUMN interactions.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN interactions.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN interactions.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN monitoring_campaigns.title IS 'Título de la campaña (ej. Campaña Vacunación y Salud El Alto 2026)'")
    op.execute("COMMENT ON COLUMN monitoring_campaigns.description IS 'Objetivo y alcance de la campaña'")
    op.execute("COMMENT ON COLUMN monitoring_campaigns.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN monitoring_campaigns.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN monitoring_campaigns.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN monitoring_targets.target_percentage IS 'Porcentaje objetivo de participación de la unidad (ej. 80%)'")
    op.execute("COMMENT ON COLUMN monitoring_targets.target_count IS 'Cantidad fija esperada de interacciones (opcional)'")
    op.execute("COMMENT ON COLUMN monitoring_targets.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN monitoring_targets.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN monitoring_targets.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN organizational_units.name IS 'Nombre de la unidad (ej. Dirección de Comunicación Social)'")
    op.execute("COMMENT ON COLUMN organizational_units.code IS 'Código identificador institucional corto'")
    op.execute("COMMENT ON COLUMN organizational_units.parent_id IS 'Referencia a unidad superior jerárquica (nullable para raíz)'")
    op.execute("COMMENT ON COLUMN organizational_units.status IS 'Estado: ACTIVE / INACTIVE'")
    op.execute("COMMENT ON COLUMN organizational_units.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN organizational_units.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN organizational_units.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN permissions.code IS 'Código único del permiso (ej. users:create)'")
    op.execute("COMMENT ON COLUMN permissions.description IS 'Descripción de la acción autorizada'")
    op.execute("COMMENT ON COLUMN permissions.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN permissions.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN permissions.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN positions.title IS 'Denominación del cargo'")
    op.execute("COMMENT ON COLUMN positions.code IS 'Código interno del cargo'")
    op.execute("COMMENT ON COLUMN positions.status IS 'Estado: ACTIVE / INACTIVE'")
    op.execute("COMMENT ON COLUMN positions.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN positions.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN positions.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN publications.external_post_id IS 'Identificador único del post en la red social (Facebook/TikTok)'")
    op.execute("COMMENT ON COLUMN publications.post_url IS 'Enlace directo a la publicación'")
    op.execute("COMMENT ON COLUMN publications.published_at IS 'Fecha y hora de publicación en UTC'")
    op.execute("COMMENT ON COLUMN publications.content_text IS 'Texto o descripción del post'")
    op.execute("COMMENT ON COLUMN publications.media_type IS 'Tipo de medio: POST, VIDEO, REEL, PHOTO'")
    op.execute("COMMENT ON COLUMN publications.is_monitored IS 'Indica si se deben capturar interacciones de esta publicación'")
    op.execute("COMMENT ON COLUMN publications.last_sync_at IS 'Timestamp UTC de la última sincronización'")
    op.execute("COMMENT ON COLUMN publications.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN publications.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN publications.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN report_executions.report_type IS 'Tipo de reporte: CAMPAIGN_COVERAGE, ORG_UNIT_INTERACTIONS, EMPLOYEE_INTERACTIONS, VERIFICATION_STATUS, SYNC_ACTIVITY'")
    op.execute("COMMENT ON COLUMN report_executions.report_version IS 'Versión del algoritmo generador'")
    op.execute("COMMENT ON COLUMN report_executions.requested_by_user_id IS 'Usuario solicitante'")
    op.execute("COMMENT ON COLUMN report_executions.generated_at IS 'Timestamp UTC de generación'")
    op.execute("COMMENT ON COLUMN report_executions.parameters IS 'Parámetros de filtrado exactos usados para garantizar reproducibilidad'")
    op.execute("COMMENT ON COLUMN report_executions.file_hash IS 'Hash criptográfico SHA-256 del archivo .xlsx generado'")
    op.execute("COMMENT ON COLUMN report_executions.file_path IS 'Ruta interna de almacenamiento del archivo'")
    op.execute("COMMENT ON COLUMN report_executions.row_count IS 'Número total de filas de datos generadas'")
    op.execute("COMMENT ON COLUMN report_executions.status IS 'Estado: GENERATING, COMPLETED, FAILED'")
    op.execute("COMMENT ON COLUMN report_executions.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN report_executions.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN report_executions.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN roles.name IS 'Nombre único del rol constitucional'")
    op.execute("COMMENT ON COLUMN roles.description IS 'Descripción del alcance del rol'")
    op.execute("COMMENT ON COLUMN roles.is_system IS 'Indica si es un rol constitucional protegido'")
    op.execute("COMMENT ON COLUMN roles.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN roles.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN roles.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN social_accounts.employee_id IS 'Funcionario al que está vinculada la cuenta'")
    op.execute("COMMENT ON COLUMN social_accounts.platform_id IS 'Plataforma de red social'")
    op.execute("COMMENT ON COLUMN social_accounts.external_user_id IS 'ID técnico permanente asignado por la plataforma social'")
    op.execute("COMMENT ON COLUMN social_accounts.current_username IS 'Nombre de usuario o @handle visible actual'")
    op.execute("COMMENT ON COLUMN social_accounts.profile_url IS 'URL del perfil en la red social'")
    op.execute("COMMENT ON COLUMN social_accounts.binding_status IS 'Estado: ACTIVE, INACTIVE, PENDING_VERIFICATION, DISPUTED'")
    op.execute("COMMENT ON COLUMN social_accounts.verified_at IS 'Fecha y hora de verificación de la vinculación'")
    op.execute("COMMENT ON COLUMN social_accounts.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN social_accounts.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN social_accounts.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN social_connector_configs.platform_name IS 'Identificador: FACEBOOK o TIKTOK'")
    op.execute("COMMENT ON COLUMN social_connector_configs.target_account_id IS 'ID de página o Handle oficial (ej. @AlcaldiaElAlto / 10006456789)'")
    op.execute("COMMENT ON COLUMN social_connector_configs.display_name IS 'Nombre descriptivo institucional'")
    op.execute("COMMENT ON COLUMN social_connector_configs.access_token_encrypted IS 'Token de acceso oficial o clave de sesión cifrada'")
    op.execute("COMMENT ON COLUMN social_connector_configs.api_secret_encrypted IS 'App Secret o cookie/session de extracción cifrada'")
    op.execute("COMMENT ON COLUMN social_connector_configs.extraction_mode IS 'OFFICIAL_API, HYBRID_SCRAPER, MANUAL_ASSISTED'")
    op.execute("COMMENT ON COLUMN social_connector_configs.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN social_connector_configs.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN social_connector_configs.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN social_platforms.name IS 'Identificador canónico de la plataforma (ej. FACEBOOK, TIKTOK)'")
    op.execute("COMMENT ON COLUMN social_platforms.display_name IS 'Nombre legible (ej. Facebook / Meta)'")
    op.execute("COMMENT ON COLUMN social_platforms.is_active IS 'Indica si la plataforma está habilitada para monitoreo'")
    op.execute("COMMENT ON COLUMN social_platforms.api_version IS 'Versión de API actualmente utilizada'")
    op.execute("COMMENT ON COLUMN social_platforms.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN social_platforms.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN social_platforms.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN username_history.previous_username IS 'Username anterior'")
    op.execute("COMMENT ON COLUMN username_history.new_username IS 'Nuevo username'")
    op.execute("COMMENT ON COLUMN username_history.changed_at IS 'Timestamp UTC de detección o registro del cambio'")
    op.execute("COMMENT ON COLUMN username_history.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN users.email IS 'Correo electrónico institucional único'")
    op.execute("COMMENT ON COLUMN users.full_name IS 'Nombre completo del usuario'")
    op.execute("COMMENT ON COLUMN users.password_hash IS 'Hash seguro Argon2id de la contraseña'")
    op.execute("COMMENT ON COLUMN users.is_active IS 'Indica si la cuenta está habilitada (baja lógica)'")
    op.execute("COMMENT ON COLUMN users.failed_login_attempts IS 'Contador de intentos fallidos consecutivos'")
    op.execute("COMMENT ON COLUMN users.locked_until IS 'Bloqueo temporal hasta timestamp UTC si supera intentos fallidos'")
    op.execute("COMMENT ON COLUMN users.last_login_at IS 'Timestamp UTC del último inicio de sesión exitoso'")
    op.execute("COMMENT ON COLUMN users.assigned_direction IS 'Dirección o dependencia superior asignada al usuario para panel individual'")
    op.execute("COMMENT ON COLUMN users.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN users.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN users.id IS 'Identificador único UUIDv4'")
    op.execute("COMMENT ON COLUMN verifications.interaction_id IS 'Interacción auditada'")
    op.execute("COMMENT ON COLUMN verifications.employee_id IS 'Identificador único inmutable del funcionario'")
    op.execute("COMMENT ON COLUMN verifications.verification_status IS 'Estado epistémico: CONFIRMED, NOT_FOUND, NOT_OBSERVABLE, DECLARED_CONFIRMED, API_RESTRICTED'")
    op.execute("COMMENT ON COLUMN verifications.verification_method IS 'Método: AUTOMATIC_CROSS_REFERENCE, MANUAL_OPERATOR, BULK_IMPORT'")
    op.execute("COMMENT ON COLUMN verifications.verified_at IS 'Fecha y hora de emisión del dictamen de verificación'")
    op.execute("COMMENT ON COLUMN verifications.verified_by_user_id IS 'Usuario operador o sistema/worker que verificó'")
    op.execute("COMMENT ON COLUMN verifications.explanation IS 'Explicación humana y técnica del estado asignado (Principio XXVIII)'")
    op.execute("COMMENT ON COLUMN verifications.evidence_id IS 'Evidencia adjunta cuando aplica'")
    op.execute("COMMENT ON COLUMN verifications.created_at IS 'Timestamp de creación en UTC'")
    op.execute("COMMENT ON COLUMN verifications.updated_at IS 'Timestamp de última actualización en UTC'")
    op.execute("COMMENT ON COLUMN verifications.id IS 'Identificador único UUIDv4'")

def downgrade() -> None:
    # Los comentarios son documentacion: no hay nada que revertir.
    pass
